In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Used Car Dataset.csv")
data

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,1548,2020 Hyundai Creta SX Opt Diesel AT BSVI,Aug-20,Comprehensive,Diesel,5,35000,First Owner,Automatic,2020,1493.00,11345.0,11345.0,250.0,17.41
1549,1549,2022 Renault KWID 1.0 RXL Opt BSVI,2022,Third Party insurance,Petrol,5,10000,999 cc,2022,Power Steering,999.00,6706.0,6706.0,91.0,3.98
1550,1550,2017 Honda WR-V i-VTEC S,Jun-17,Comprehensive,Petrol,5,49000,First Owner,Manual,2017,17.50,1199.0,1199.0,887.0,5.85
1551,1551,2018 Volkswagen Polo 1.0 MPI Comfortline,May-18,Comprehensive,Petrol,5,40000,Second Owner,Manual,2018,18.78,999.0,999.0,75.0,4.75
1552,1552,2018 Maruti Swift Dzire VXI,May-18,Comprehensive,Petrol,5,34756,First Owner,Manual,2018,20.85,1197.0,1197.0,8314.0,6.10

In [3]:
data.columns

Index(['Unnamed: 0', 'car_name', 'registration_year', 'insurance_validity',
       'fuel_type', 'seats', 'kms_driven', 'ownsership', 'transmission',
       'manufacturing_year', 'mileage(kmpl)', 'engine(cc)', 'max_power(bhp)',
       'torque(Nm)', 'price(in lakhs)'],
      dtype='object')

## Data Cleaning

In [4]:
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data.drop(["max_power(bhp)"],axis=1,inplace=True)
data=data[~data["registration_year"].str.isnumeric()]
data=data[data["manufacturing_year"].str.isnumeric()]

In [5]:
data["registration_year"]

0       Jul-17
1       Jan-21
2       Sep-18
3       Dec-19
4       Aug-19
         ...
1547    May-22
1548    Aug-20
1550    Jun-17
1551    May-18
1552    May-18
Name: registration_year, Length: 1408, dtype: object

In [6]:
data["registration_year"]=data["manufacturing_year"]+' '+data["registration_year"].str.split('-').str.get(0)

In [7]:
data["registration_year"]=pd.to_datetime(data["registration_year"])

C:\Users\sayan\AppData\Local\Temp\ipykernel_10952\1217795317.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data["registration_year"]=pd.to_datetime(data["registration_year"])

In [8]:
# data["registration_year"]=data["manufacturing_year"].astype('int')

In [9]:
data["registration_year"]

0      2017-07-01
1      2020-01-01
2      2018-09-01
3      2019-12-01
4      2019-08-01
          ...
1547   2022-05-01
1548   2020-08-01
1550   2017-06-01
1551   2018-05-01
1552   2018-05-01
Name: registration_year, Length: 1408, dtype: datetime64[ns]

In [10]:
data=data.drop("manufacturing_year",axis=1)

In [11]:
data["car_name"]=data["car_name"].str.split(' ').str.slice(1,-1).str.join(" ")

In [12]:
data

,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,mileage(kmpl),engine(cc),torque(Nm),price(in lakhs)
0,Mercedes-Benz S-Class,2017-07-01,Comprehensive,Petrol,5,56000,First Owner,Automatic,7.81,2996.0,333.0,63.75
1,Nissan Magnite Turbo CVT XV Premium Opt,2020-01-01,Comprehensive,Petrol,5,30615,First Owner,Automatic,17.40,999.0,9863.0,8.99
2,BMW X1 sDrive 20d,2018-09-01,Comprehensive,Diesel,5,24000,First Owner,Automatic,20.68,1995.0,188.0,23.75
3,Kia Seltos GTX,2019-12-01,Comprehensive,Petrol,5,18378,First Owner,Manual,16.50,1353.0,13808.0,13.56
4,Skoda Superb LK 1.8 TSI,2019-08-01,Comprehensive,Petrol,5,44900,First Owner,Automatic,14.67,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1547,Maruti Ertiga VXI,2022-05-01,Third Party insurance,CNG,7,26500,First Owner,Manual,26.11,1462.0,8663.0,11.50
1548,Hyundai Creta SX Opt Diesel AT,2020-08-01,Comprehensive,Diesel,5,35000,First Owner,Automatic,1493.00,11345.0,250.0,17.41
1550,Honda WR-V i-VTEC,2017-06-01,Comprehensive,Petrol,5,49000,First Owner,Manual,17.50,1199.0,887.0,5.85
1551,Volkswagen Polo 1.0 MPI,2018-05-01,Comprehensive,Petrol,5,40000,Second Owner,Manual,18.78,999.0,75.0,4.75
1552,Maruti Swift Dzire,2018-05-01,Comprehensive,Petrol,5,34756,First Owner,Manual,20.85,1197.0,8314.0,6.10

In [13]:
data=data.reset_index(drop=True)

In [14]:
data

,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,mileage(kmpl),engine(cc),torque(Nm),price(in lakhs)
0,Mercedes-Benz S-Class,2017-07-01,Comprehensive,Petrol,5,56000,First Owner,Automatic,7.81,2996.0,333.0,63.75
1,Nissan Magnite Turbo CVT XV Premium Opt,2020-01-01,Comprehensive,Petrol,5,30615,First Owner,Automatic,17.40,999.0,9863.0,8.99
2,BMW X1 sDrive 20d,2018-09-01,Comprehensive,Diesel,5,24000,First Owner,Automatic,20.68,1995.0,188.0,23.75
3,Kia Seltos GTX,2019-12-01,Comprehensive,Petrol,5,18378,First Owner,Manual,16.50,1353.0,13808.0,13.56
4,Skoda Superb LK 1.8 TSI,2019-08-01,Comprehensive,Petrol,5,44900,First Owner,Automatic,14.67,1798.0,17746.0,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1403,Maruti Ertiga VXI,2022-05-01,Third Party insurance,CNG,7,26500,First Owner,Manual,26.11,1462.0,8663.0,11.50
1404,Hyundai Creta SX Opt Diesel AT,2020-08-01,Comprehensive,Diesel,5,35000,First Owner,Automatic,1493.00,11345.0,250.0,17.41
1405,Honda WR-V i-VTEC,2017-06-01,Comprehensive,Petrol,5,49000,First Owner,Manual,17.50,1199.0,887.0,5.85
1406,Volkswagen Polo 1.0 MPI,2018-05-01,Comprehensive,Petrol,5,40000,Second Owner,Manual,18.78,999.0,75.0,4.75
1407,Maruti Swift Dzire,2018-05-01,Comprehensive,Petrol,5,34756,First Owner,Manual,20.85,1197.0,8314.0,6.10

In [15]:
data.describe()

,registration_year,seats,kms_driven,mileage(kmpl),engine(cc),torque(Nm),price(in lakhs)
count,1408,1408.000000,1408.000000,1405.000000,1.405000e+03,1.404000e+03,1408.000000
mean,2018-01-01 05:39:32.727272704,5.197443,51904.819602,191.159950,1.623757e+10,1.281822e+04,181.851442
min,2009-01-01 00:00:00,4.000000,620.000000,7.810000,5.000000e+00,1.900000e+01,1.050000
25%,2016-01-01 00:00:00,5.000000,29502.000000,16.350000,1.197000e+03,5.100000e+02,4.740000
50%,2018-05-01 00:00:00,5.000000,49067.000000,18.900000,1.462000e+03,1.213000e+03,6.950000
75%,2020-01-01 00:00:00,5.000000,69004.500000,21.400000,1.995000e+03,8.873000e+03,16.500000
max,2023-11-01 00:00:00,8.000000,810000.000000,3996.000000,3.258640e+12,1.186600e+06,95000.000000
std,NaN,0.625853,39976.736374,525.455339,2.295181e+11,8.273379e+04,3653.354519

In [16]:
data=data[data["price(in lakhs)"]<100.000000].reset_index(drop=True)

In [17]:
data.to_csv("clean.csv")

## Model

In [18]:
data=data.dropna()
x=data.drop(columns="price(in lakhs)")
y=data["price(in lakhs)"]

## RandomForestRegressor Aproch

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
data["seats"].value_counts()

seats
5    1225
7     138
4      20
6      16
8       2
Name: count, dtype: int64

In [21]:
data["mileage(kmpl)"].value_counts()

mileage(kmpl)
18.90      55
1197.00    49
18.60      35
21.40      33
18.00      29
           ..
13.79       1
19.70       1
22.15       1
17.74       1
18.78       1
Name: count, Length: 312, dtype: int64

In [22]:
data["car_name"].value_counts()

car_name
Hyundai Grand i10                   42
Maruti Baleno 1.2                   34
Maruti Baleno                       25
Maruti Swift Dzire                  20
Maruti Swift                        18
                                    ..
Mahindra Alturas G4 4X2              1
BMW 5 Series 520d Sport              1
Maruti Ignis 1.2 Delta               1
Mahindra XUV700 AX5 7 Str Diesel     1
Hyundai Creta SX Opt Diesel AT       1
Name: count, Length: 545, dtype: int64

In [23]:
data.head()

,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,mileage(kmpl),engine(cc),torque(Nm),price(in lakhs)
0,Mercedes-Benz S-Class,2017-07-01,Comprehensive,Petrol,5,56000,First Owner,Automatic,7.81,2996.0,333.0,63.75
1,Nissan Magnite Turbo CVT XV Premium Opt,2020-01-01,Comprehensive,Petrol,5,30615,First Owner,Automatic,17.40,999.0,9863.0,8.99
2,BMW X1 sDrive 20d,2018-09-01,Comprehensive,Diesel,5,24000,First Owner,Automatic,20.68,1995.0,188.0,23.75
3,Kia Seltos GTX,2019-12-01,Comprehensive,Petrol,5,18378,First Owner,Manual,16.50,1353.0,13808.0,13.56
4,Skoda Superb LK 1.8 TSI,2019-08-01,Comprehensive,Petrol,5,44900,First Owner,Automatic,14.67,1798.0,17746.0,24.00

In [24]:
# from sklearn.preprocessing import StandardScaler
# scler=StandardScaler()
# d=data[["seats","kms_driven","mileage(kmpl)","engine(cc)","torque(Nm)"]]
# sl=scler.fit_transform(d)
# sl_data_fream=pd.DataFrame(sl,columns=["seats","kms_driven","mileage(kmpl)","engine(cc)","torque(Nm)"])
# sl_data_fream
# # have error
# data.update(data.columns["seats","kms_driven","mileage(kmpl)","engine(cc)","torque(Nm)"],sl_data_fream)
# data

In [25]:
categori=["car_name","registration_year","insurance_validity","fuel_type",
          "seats","ownsership","transmission","mileage(kmpl)","engine(cc)","torque(Nm)"]

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_transformer
one_hot=OneHotEncoder()
transfrom=ColumnTransformer([("one_hot",
                                     one_hot,
                                     categori)],
                                    remainder='passthrough')
x_transfrom=transfrom.fit_transform(x)

print(x_transfrom.toarray())

[[    0.     0.     0. ...     0.     0. 56000.]
 [    0.     0.     0. ...     0.     0. 30615.]
 [    0.     0.     0. ...     0.     0. 24000.]
 ...
 [    0.     0.     0. ...     0.     0. 49000.]
 [    0.     0.     0. ...     0.     0. 40000.]
 [    0.     0.     0. ...     0.     0. 34756.]]

In [27]:
t=pd.DataFrame(x_transfrom.toarray())
# t_f_d=pd.DataFrame(x_transfrom)
# t_f_d.reset_index(drop=True)
# t=t.reset_index(drop=True)
# t_f_d
print(t)

      0     1     2     3     4     5     6     7     8     9     ...  1416  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...
1396   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0
1397   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0
1398   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0
1399   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0
1400   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0

      1417  1418  1419  1420  1421  1422  1423  1424     1425
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  56000.0
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  30615.0
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  24000.0
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  18378.0
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  44900.0
...    ...   ...   ...   ...   ...   ...   ...   ...      ...
1396   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  26500.0
1397   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  35000.0
1398   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  49000.0
1399   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  40000.0
1400   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  34756.0

[1401 rows x 1426 columns]

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(t,y,test_size=0.2)

In [29]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline

In [30]:

score=[]
for i in range(5):
    x_train,x_test,y_train,y_test=train_test_split(t,y,test_size=0.2)
    model=RandomForestRegressor()
    model.fit(x_train,y_train)
    y_pred=model.score(x_test,y_test)
    score.append(y_pred)

In [31]:
max(score)

0.8805730216486062

In [32]:
import numpy as np
x_train,x_test,y_train,y_test=train_test_split(t,y,test_size=0.2,random_state=np.argmax(score))
model=RandomForestRegressor()
model.fit(x_train,y_train)
y_pred=model.score(x_test,y_test)
y_pred

0.8833672216248158

In [33]:
import pickle

pickle.dump(model, open('RandomForestRegressor_model.pkl','wb'))
pickle.dump(transfrom, open('RandomForestRegressor_transfrom.pkl','wb'))

In [34]:

import datetime
d=datetime.datetime.strptime('2010-10-1','%Y-%m-%d')
# type(d)
d=pd.DataFrame([['Maruti Swift Dzire',d,'Comprehensive','Petrol',5,30615,'First Owner',
                             'Automatic',17.40,999.0,8314.0]],
                             columns=['car_name','registration_year','insurance_validity','fuel_type','seats','kms_driven',
                                    'ownsership','transmission','mileage(kmpl)','engine(cc)','torque(Nm)'])
d_trnas=transfrom.transform(d)

# x_test
model.predict(d_trnas)

array([11.1033])

## Second Aproch   Linear Regression

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split

In [36]:
on=OneHotEncoder()
on.fit_transform(x[['car_name','registration_year','insurance_validity',
          'fuel_type','seats','kms_driven','ownsership',
          'transmission','mileage(kmpl)','engine(cc)','torque(Nm)']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15411 stored elements and shape (1401, 2120)>

In [37]:
colum_trnas=make_column_transformer((OneHotEncoder(categories=on.categories_),['car_name','registration_year',
                                                                               'insurance_validity','fuel_type','seats',
                                                                               'kms_driven','ownsership','transmission',
                                                                               'mileage(kmpl)','engine(cc)','torque(Nm)']),
                                                                                remainder='passthrough')
colum_trnas

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(categories=[array(['Audi A3 35 TDI Premium', 'Audi A4 2.0', 'Audi A4 2.0 TDI Premium',
       'Audi A4 30 TFSI', 'Audi A4 30 TFSI Premium', 'Audi A4 35 TDI',
       'Audi A6 2.0 TDI Premium', 'Audi A6 35',
       'Audi A6 45 TFSI Technology', 'Audi A8 L 3.0 TDI', 'Audi Q2',
       'Audi Q2 Premium Plus', 'Audi Q3 30 TFSI Premium',
       'Audi Q3 35 TDI Q...
       2.61490e+04, 2.61500e+04, 2.65300e+04, 2.81610e+04, 2.96360e+04,
       3.01730e+04, 3.08430e+04, 3.28550e+04, 3.35250e+04, 3.62070e+04,
       3.68780e+04, 5.76630e+04, 1.08495e+05, 8.05200e+05, 9.04000e+05,
       1.18660e+06])]),
                                 ['car_name', 'registration_year',
                                  'insurance_validity', 'fuel_type', 'seats',
                                  'kms_driven', 'ownsership', 'transmission',
                                  'mileage(kmpl)', 'engine(cc)',
                                  'torque(Nm)'])])

In [38]:
scores=[]
for i in range(300):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(colum_trnas,lr)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    scores.append(r2_score(y_test,y_pred))

In [39]:
max(scores)

0.8535989393975365

In [40]:
import numpy as np

In [41]:
np.argmax(scores)

np.int64(187)

In [42]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(colum_trnas,lr)
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
scores.append(r2_score(y_test,y_pred))

In [43]:
import pickle

pickle.dump(pipe, open('LinerRegration_model.pkl','wb'))

In [44]:
import datetime
d=datetime.datetime.strptime('2018-10-1','%Y-%m-%d')
# type(d)
pipe.predict(pd.DataFrame([['Skoda Superb LK 1.8 TSI',d,'Comprehensive','Petrol',5,30615,'First Owner','Automatic',17.40,999.0,8314.0]],columns=['car_name','registration_year','insurance_validity','fuel_type','seats','kms_driven','ownsership','transmission','mileage(kmpl)','engine(cc)','torque(Nm)']))

array([15.41380071])